# BigBang

hostname: dev.bigbang.mil
istio:
  enabled: false
  hardened:
    # when this gets enabled by default, packages that use redis as a dependency will need to disable it and provide their own policies
    enabled: false
    outboundTrafficPolicyMode: "REGISTRY_ONLY"
    customServiceEntries: []
      # - name: "allow-google"
      #   enabled: true
      #   spec:
      #     hosts:
      #       - google.com
      #     location: MESH_EXTERNAL
      #     ports:
      #       - number: 443
      #         protocol: TLS
      #         name: https
      #     resolution: DNS

    customAuthorizationPolicies: []
    # - name: "allow-nothing"
    #   enabled: true
    #   spec: {}
  redis:
    # due to the complexity around this configuration, the redis virtual service is disabled by default
    enabled: false
    labels: {}
    annotations: {}
    gateway:
      port: 15443
    # TCP connections don't have host headers, so * is required
    hosts:
      - "*"

monitoring:
  enabled: false

# Deletes previous statefulsets before attempting an upgrade
# May be required on some Redis chart updates due to upstream breaking changes
# REQUIRED for Chart v14 upgrade
cleanUpgrade:
  enabled: false
  image: "registry1.dso.mil/ironbank/big-bang/base:2.1.0"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m

# NOTE: We default this to true in case packages consuming Redis forget to turn it on and have API traffic blocked
# This has been corrected as networkPolicy and moved the controlPlaneCidr section to the networkPolicy block.
networkPolicies:
  enabled: true
  controlPlaneCidr: 0.0.0.0/0


# -- Values to pass to [the upstream redis chart](https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml)
# @default -- Upstream chart values
upstream:
  nameOverride: "redis-bb"
  fullnameOverride: "redis-bb"
  global:
    imagePullSecrets:
      - private-registry
    security:
      allowInsecureImages: true
  image:
    registry: registry1.dso.mil
    repository: ironbank/bitnami/redis
    tag: 8.2.2
  master:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m

  replica:
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: true
  sentinel:
    image:
      tag: 8.0.2-debian-12-r2
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
  networkPolicy:
    enabled: false
    controlPlaneCidr: 0.0.0.0/0
  metrics:
    image:
      registry: registry1.dso.mil
      repository: ironbank/bitnami/analytics/redis-exporter
      tag: v1.78.0
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
    serviceMonitor:
      scheme: ""
  volumePermissions:
    image:
      tag: 12-debian-12-r46
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
    containerSecurityContext:
      capabilities:
        drop:
          - ALL
  kubectl:
    enabled: false
    image:
      tag: 1.33.1-debian-12-r5
    resources:
      limits:
        memory: 256Mi
        cpu: 100m
      requests:
        memory: 256Mi
        cpu: 100m
  sysctl:
    image:
      tag: 12-debian-12-r46
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
