{{- if and .Values.istio.enabled .Values.istio.redis.enabled -}}
{{- $uncleanChartName := printf "%s-%s" .Chart.Name .Chart.Version -}}
{{- $chartName := regexReplaceAll "\\+" $uncleanChartName "_" -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ default "redis-bb" (dig "nameOverride" nil .Values.upstream) }}
    helm.sh/chart: {{ $chartName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: redis
    app.kubernetes.io/component: networking
    {{- if .Values.istio.redis.labels }}
    {{ toYaml .Values.istio.redis.labels | indent 4 }}
    {{- end }}
  {{- if .Values.istio.redis.annotations }}
  annotations:
  {{ toYaml .Values.istio.redis.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  - redis-gateway
  hosts:
  {{- range .Values.istio.redis.hosts }}
    - {{  . | quote }}
  {{- end }}
  tcp:
  - match:
    - port: {{ .Values.istio.redis.gateway.port }}
    route:
    - destination:
        port:
          number: {{ .Values.upstream.master.containerPorts.redis }}
        host: {{ printf "%s-master" (default "redis-bb" (dig "fullnameOverride" nil .Values.upstream)) }}
{{- end }}
