{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.redis.enabled -}}
{{- $namespace := $.Release.Namespace -}}
{{- $name := "redis-gateway" -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $name }}-ingressgateway-authz-policy
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ $namespace }}
        principals:
        - "cluster.local/ns/{{ $namespace }}/sa/{{ $name }}-ingressgateway-service-account"
{{- end }}
